### ISSUE TITLE
how to set next's _config.yml when using hexo-next

### ISSUE THREAD

**Issue by sli1989** [wzpan/hexo-renderer-pandoc#16]
in version 0.2.1, adding `if(config.template) args.push("--template=" + config.template);` leads to `TypeError: Cannot read property 'template' of undefined` when `hexo generate`...

how to set pandoc in ` _config.yml `, thank you for your help.

```
pandoc:
  filters:
  extra:
  template:
  meta:
  mathEngine:
```

1. `mathjax:   enable: true` in the theme's `_config.yml`, 
1. `npm uninstall hexo-renderer-marked --save`
1. `npm install hexo-renderer-pandoc --save` 
1. `hexo g` failed
1. **Remove** `the if(config.template) args.push("--template=" + config.template);` in `hexo\node_modules\hexo-renderer-pandoc\index.js` , 
1. `hexo g` passed

**Comment by sli1989** [comment]
you can close the issue.
if you want to use `hexo-renderer-pandoc`(new version) in hexo , you must add default configuration in the **site**'s `_config.yml` not the theme's.

```
pandoc:
  filters:
  extra:
  template: 
  meta:
  mathEngine:
```
