### ISSUE TITLE
readme.md中bibliography前未加-，另外生成的参考文献中没有标题

### ISSUE THREAD

**Issue by sd44** [wzpan/hexo-renderer-pandoc#23]
1，bib遗漏了-

```
pandoc:
  filters:
    - pandoc-citeproc
  extra:
    bibliography: "/path/to/bibfile.bib"
```

2. 可能是pandoc的问题，而非本插件的问题 -___-。
我设置如下，参考文献正常，但是title无法生成。必须自己在md文件中写入节标题吗？
```
# hexo-renderer-pandoc
pandoc:
  filters:
    - pandoc-citeproc
  extra:
    - bibliography: "/home/sd44/xueshu/dingjia/ref/refs.bib"
  meta:
    - link-citations: true
    - reference-section-title:“Reference”
```

3，关于freemind主题的，能否让右侧目录可以随着下拉而滚动？

4，没想到这个包也是wzpan写的，哈哈，一直在用你的主题……
