### ISSUE TITLE
回车换行不起作用

### ISSUE THREAD

**Issue by soundmemories** [wzpan/hexo-renderer-pandoc#53]
请问能否像hexo-renderer-marked一样支持回车换行，而不是在每句话结尾加上2个以上空格才换行呢？

**Comment by Ritsuka314** [comment]
The issue is related to pandoc itself rather than to this plugin. As far as I am aware of, pandoc does not offer the required functionality. However, you might be interested by pandoc's [escaped_line_breaks` extension](https://pandoc.org/MANUAL.html#extension-escaped_line_breaks), which is enabled by default

**Comment by soundmemories** [comment]
谢谢，我在您提供的pandoc文档中找到了`hard_line_breaks`这个扩展，但是在_config.yml没有找到extensions这个参数，似乎这个插件支持下面的参数：
```
pandoc:
  filters:
  extra:
  template:
  meta:
  mathEngine:
```
目前我只能在index.js中添加它，这样才起作用：
`args = [ '-f', 'markdown-smart+'+'hard_line_breaks'+extensions, '-t', 'html-smart', math]`
希望后续能支持在_config.yml中添加这个参数。

**Comment by Ritsuka314** [comment]
拓展可以通過 `_config.yml` 配置．我已更新 readme 文檔如下：

``` yml
pandoc:
  extensions:
  filters:
  extra:
  template:
  meta:
  mathEngine:
```

- extensions is a list of [markdown extensions](https://pandoc.org/MANUAL.html#extensions)
