### ISSUE TITLE
How to escape dollar signs?

### ISSUE THREAD

**Issue by TripleCamera** [wzpan/hexo-renderer-pandoc#61]
How to escape dollar signs if I don't want math formulas?

Source code:
```md
$math$

\$escaped math\$

\\$double escaped math\\$
```

Output: All of them are displayed as math formulas. The third one has a backslash at the beginning.

`_config.yml`:
```yml
pandoc:
  args:
    - "-f"
    - "gfm"
    - "-t"
    - "html"
    - "--mathjax"
```

`_config.next.yml`:
```yml
math:
  mathjax:
    enable: true
```
