### ISSUE TITLE
pandoc 不支持 GFM 格式，转换成 html 失去 [!TIP] 等提示框

### ISSUE THREAD

**Issue by longluo** [wzpan/hexo-renderer-pandoc#63]
### Check List

- [X] I have already read README.
- [X] I have already searched existing issues.
- [X] I have already searched existing pull requrests.

### Feature Request

pandoc 不支持 GFM 格式，转换成 html 失去 [!TIP] 等提示框

GFM 在typora中是可以正常显示  [!TIP] 等提示框的，但是转换成 html 就显示不好，请问可以改进下吗？

**Comment by uiolee** [comment]
If pandoc does not support it, you should submit an issue to pandoc.

**Comment by uiolee** [comment]
pandoc already supports "gfm". It you want, you should specify the `gfm` parameter to enable it.

**Comment by longluo** [comment]
I had set parameter  `gfm` but it still not works.

**Comment by longluo** [comment]
I had tried to set parameter `gfm`, but it still not works.

**Comment by uiolee** [comment]
can't reproduce. show me your case

**Comment by longluo** [comment]
I use this, but it doesn't woks.

```txt
pandoc:
  args:
    - "-f"
    - "gfm"
    - "-t"
    - "html"
    - "--mathjax"
```

**Comment by uiolee** [comment]
`hexo-renderer-pandoc` and `pandoc` output the same result, there is no problem.

```yml _config.yml
# _config.yml
pandoc:
  args:
    - "-f"
    - "gfm"
    - "-t"
    - "html"
    - "--mathjax"

```

```markdown post

## Test

> [!TIP]
> Helpful advice for doing things better or more easily.

AAAAAAAAAAA

## QQQQQQQQQQ

fwagvewgehjufhiu
```

![preview](https://github.com/hexojs/hexo-renderer-pandoc/assets/22849383/0426092e-d36f-44ac-ba5b-d1bbec11062d)

**Comment by longluo** [comment]
but the rendered html is this：

![捕获1](https://github.com/hexojs/hexo-renderer-pandoc/assets/3395062/357098d8-9dd6-4430-987d-7a3b7805d3b4)

what we want to rendered out result is:

![捕获2](https://github.com/hexojs/hexo-renderer-pandoc/assets/3395062/d99d74d3-a3da-4249-9fb2-d5f7611b6ce9)

**Comment by longluo** [comment]
This problem is not closed.

**Comment by Ritsuka314** [comment]
Cannot reproduce; I got same result as @uiolee 

![image](https://github.com/hexojs/hexo-renderer-pandoc/assets/14881706/940ab8cf-0bac-4033-8092-587f86f668c1)

@longluo Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Please start from scratch (i.e., `hexo init` in an empty directory) and include in your reply the following:

- `package.json` with as few as dependencies as possible
- `_config.yml`
- A minimal source `.md`

Please report the output of the following command: `pandoc --version`.

**Comment by longluo** [comment]
`package.json`:

```txt
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "7.2.0"
  },
  "dependencies": {
    "hexo": "^7.0.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-pandoc": "^0.4.0",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^1.0.0"
  }
}
```

`_config.xml`:

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# Pandoc Path
# Used to render the Math LaTeX equations
pandoc:
  args:
    - "-f"
    - "gfm"
    - "-t"
    - "html"
    - "--mathjax"
```

`pandoc` version:

```
pandoc.exe 3.1.13
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: 
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

The outpus is this:

![tip3](https://github.com/hexojs/hexo-renderer-pandoc/assets/3395062/d2b29818-7873-426c-94a4-2b1ea77683b4)

This is still not correct, very ugly.

I want to render result like typora.
